name: Check commits for compliance with conventional commit spec

on:
  - push

jobs:
  cogCheck:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Conventional commits check
        uses: oknozor/cocogitto-action@390bda87a19bf627e03ad075c67a11e9ddbb7547 # v4
        with:
          command: check
