name: Create Release PR for containers

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - images/**

jobs:
  createReleasePR:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7 # v4
        with:
          skip-github-release: true
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
        id: release-please
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        if: ${{ steps.release-please.outputs.prs_created == 'true' }}
      - name: Set PRs to auto-merge
        if: ${{ steps.release-please.outputs.prs_created == 'true' }}
        run: |
          for pr_number in ${PR_NUMBERS};do
            gh pr merge --auto --squash "$pr_number"
          done
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
          PR_NUMBERS: ${{ github.event.number }}
          merge-method: squash