name: Update CODEOWNERS
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  generateCodeowners:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: generate CODEOWNERS
        run: ./.github/scripts/sync-codeowners.sh > .github/CODEOWNERS

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7
        with:
          add-paths: |
            .github/CODEOWNERS
          commit-message: "ci: [bot] Update 'CODEOWNERS'"
          branch: ci/update-codeowners
          title: "ci: Update CODEOWNERS"
      - name: Set PR to auto-merge
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash